import TempBookImage from 'assets/image/test_book_image.jpg';

/* global BookInfromation */

export const TEMP_BOOK_DATA: BookInfromation[] = [
  {
    title: '설민석의 역사여행',
    publisher: '아무 출판사',
    author: '김재욱',
    date: '2019-01-01',
    rating: 4.5,
    review: '',
    year: [2019],
    rank: [10],
    image: TempBookImage,
    price: '30000',
    keyword: [],
    barcode: '9336523',
    success: true,
    kor: true,
  },
  {
    title: '설민석의 역사여행',
    publisher: '아무 출판사',
    author: '김재욱',
    date: '2019-01-01',
    rating: 4.5,
    review: '',
    year: [2019],
    rank: [10],
    image: TempBookImage,
    price: '30000',
    keyword: [],
    barcode: '9336523',
    success: true,
    kor: true,
  },
  {
    title: '설민석의 역사여행',
    publisher: '아무 출판사',
    author: '김재욱',
    date: '2019-01-01',
    rating: 4.5,
    review: '',
    year: [2019],
    rank: [10],
    image: TempBookImage,
    price: '30000',
    keyword: [],
    barcode: '9336523',
    success: true,
    kor: true,
  },
  {
    title: '설민석의 역사여행',
    publisher: '아무 출판사',
    author: '김재욱',
    date: '2019-01-01',
    rating: 4.5,
    review: '',
    year: [2019],
    rank: [10],
    image: TempBookImage,
    price: '30000',
    keyword: [],
    barcode: '9336523',
    success: true,
    kor: true,
  },
  {
    title: '설민석의 역사여행',
    publisher: '아무 출판사',
    author: '김재욱',
    date: '2019-01-01',
    rating: 4.5,
    review: '',
    year: [2019],
    rank: [10],
    image: TempBookImage,
    price: '30000',
    keyword: [],
    barcode: '9336523',
    success: true,
    kor: true,
  },
];
